name: Build and Provisioning

on:
  push:

env:
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}

jobs:
  setup-build-publish-deploy:

    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Build
      run: |
        make build_image